
class DataIngestionArtifact:...
class DataValidationArtifact:...
class DataTransformationArtiArtifact:...
class ModelTrainingArtifact:...
class ModelTraiingArtifact:...
class ModelEvaluationArtifact:...
class ModelPusherArtifact:...
