
class DataIngestionConfig:...
class DataValidationConfig:...
class DataTransformationConfig:...
class ModelTrainingConfig:...
class ModelTraiingConfig:...
class ModelEvaluationConfig:...
class ModelPusherConfig:...
